# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0908e727bd99f83e0013e86a13fa43d8db3c2452e5c8a193c0fec19b55ad55e7d7bfbea7cf2239ae345e8b8a2591486f000e057e13f224f44e27b2b7cd61d30a

test:
  secret_key_base: 1522a4d63e48a12762d0e7d5a32b282223a0b2f5b1b22e4538d55add2053d0fea8f11a440a82f42e23e8d28bf70552f30abb80a3c9af3ec0cc9175a89301533a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
